# Generated by Django 2.1.5 on 2019-01-20 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCacheModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='图片名称')),
                ('describe', models.TextField(verbose_name='图片描述')),
                ('photo_url', models.TextField(verbose_name='图片的路径')),
                ('thumbnail', models.ImageField(upload_to='static/data/images/cache', verbose_name='缩略图')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cuser', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'photo_cache',
            },
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='图片名称')),
                ('describe', models.TextField(verbose_name='图片描述')),
                ('photo_url', models.TextField(verbose_name='图片的路径')),
                ('thumbnail', models.ImageField(upload_to='static/user_img', verbose_name='缩略图')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
