# Generated by Django 2.1.5 on 2019-01-21 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocachemodel',
            name='thumbnail',
            field=models.TextField(verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='photocachemodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fk_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='thumbnail',
            field=models.TextField(verbose_name='缩略图'),
        ),
    ]
